# Generated by Django 5.1.4 on 2025-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=500)),
                ('molecular_weight', models.FloatField()),
                ('logp', models.FloatField()),
                ('num_h_acceptors', models.IntegerField()),
                ('num_h_donors', models.IntegerField()),
                ('num_rotatable_bonds', models.IntegerField()),
                ('num_heavy_atoms', models.IntegerField()),
                ('tpsa', models.FloatField()),
                ('qed', models.FloatField()),
                ('dynamic_properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
