# Generated by Django 5.1.4 on 2025-04-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dynamiccolumn_molecule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_id', models.UUIDField()),
                ('search_query', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=10)),
                ('source_id', models.CharField(max_length=255)),
                ('names', models.JSONField(default=list)),
                ('positions', models.JSONField(blank=True, default=list, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('listed_on', models.DateField(blank=True, null=True)),
                ('match_score', models.FloatField()),
                ('calculated_risk', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('user_defined_risk', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DynamicColumn',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Molecule',
        ),
    ]
