# Generated by Django 5.1.4 on 2025-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sanctionscreening_delete_dynamiccolumn_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_type', models.CharField(max_length=50)),
                ('matched_name', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('listed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SanctionScreening',
        ),
    ]
